In [5]:
import torch
import torch.nn as nn

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.avgpool = nn.AdaptiveAvgPool1d(1)

    def forward(self,x):
        print(x)
        x = self.avgpool(x)
        print(x)
        print(x.size())
        return x

def test():
    x = torch.Tensor([[
        [1,2,3,4,5,6],
        [7,8,9,1,2,3],
        [1,2,3,4,5,6],
        [1,2,3,4,5,6],
        [1,2,3,4,5,6],
        [1,2,3,4,5,6],
        [7,8,9,1,2,3],
        [7,8,9,1,2,3]]]
        )
    print(x.size())
    net = TestNet()
    y = net(x)
    return y

test()

torch.Size([1, 8, 6])
tensor([[[1., 2., 3., 4., 5., 6.],
         [7., 8., 9., 1., 2., 3.],
         [1., 2., 3., 4., 5., 6.],
         [1., 2., 3., 4., 5., 6.],
         [1., 2., 3., 4., 5., 6.],
         [1., 2., 3., 4., 5., 6.],
         [7., 8., 9., 1., 2., 3.],
         [7., 8., 9., 1., 2., 3.]]])
tensor([[[3.5000],
         [5.0000],
         [3.5000],
         [3.5000],
         [3.5000],
         [3.5000],
         [5.0000],
         [5.0000]]])
torch.Size([1, 8, 1])


tensor([[[3.5000],
         [5.0000],
         [3.5000],
         [3.5000],
         [3.5000],
         [3.5000],
         [5.0000],
         [5.0000]]])